### ISSUE TITLE
gzip: output/sim1/admixed_data/output/admix_afr_amer.result: No such file or directory

### ISSUE THREAD

**Issue by biona001** [taylorcavazos/PRS_Admixture_Simulation#2]
Hi, I was trying to run a smaller example, where I changed `N_CEU = 21000, N_YRI = 21000` and `M=100` in the `config.py` file. 

I got the following error
```
$ python run_simulation.py --sim 1 --snp_selection ceu --snp_weighting ceu --threads 16

Simulating populations for iteration=1
--------------------
Population Breakdown
--------------------
Number CEU: 21000
Number YRI: 21000
Number for mating: 1000
--------------------


Simulating admixed populations

Loading VCF output/sim1/admixed_data/input/ceu_yri_genos.vcf.gz chromosome 20 ...
Chromosome 20 loaded - 1361327 SNPs, 2000 samples
Breeding generation    3/   8 (37.5%) -   5000 diploid individuals     gzip: output/sim1/admixed_data/output/admix_afr_amer.query.vcf: No such file or directory
gzip: output/sim1/admixed_data/output/admix_afr_amer.result: No such file or directory
``` 

My questions are:
+ Is this a bug or if I messed up something?
+ `PRS_Admixture_Simulation/output/sim1/admixed_data/input` contains `ceu_yri_genos.vcf.gz` with only 2000 samples. Who are they? Shouldn't this file contain 42000 samples?

**Comment by taylorcavazos** [comment]
Hi @biona001! Thanks for your interest in the simulation tool and for your questions.

> Is this a bug or if I messed up something

I'm unable to replicate this error, but it looks like the computation ended before the admixed samples could be created (you should see 8/8). The process likely stopped halfway through and was unable to generate the output file. 

Can you try again with fewer samples to ensure it isn't something else? Try `N_CEU=2100`, `N_YRI=2100`, `N_MATE=100`, `N_ADMIX=500` in the config. If you are able to get this working, run the larger sample size and make sure the process is finished before any interruption. Sorry, this step can require a bit of time.

> `PRS_Admixture_Simulation/output/sim1/admixed_data/input` contains `ceu_yri_genos.vcf.gz` with only 2000 samples. Who are they? Shouldn't this file contain 42000 samples?

This folder contains only files relevant to the admixed samples so `ceu_yri_genos.vcf.gz` contains the 1000 `YRI` and the 1000 `CEU` samples that were randomly selected to generate admixed samples. 
* The full 42,000 samples (in your example) would be available here: `output/sim1/trees/tree_all.hdf`
* The 40,000 samples, 20,000 for each ancestry with the samples used for "mating" will be here: `output/sim1/trees/tree_CEU_GWAS_nofilt.hdf` and `output/sim1/trees/tree_YRI_GWAS_nofilt.hdf`.
* You'll also find useful information about samples in the `output/sim1/trees/sample_map_*.txt`

Please let me know if anything doesn't make sense!

**Comment by biona001** [comment]
Thank you! 

With `N_CEU=2100, N_YRI=2100, N_MATE=100, N_ADMIX=500`, the computation went further until a different error
```
python run_simulation.py --sim 1 --snp_selection ceu --snp_weighting ceu --threads 16

Simulating populations for iteration=1
--------------------
Population Breakdown
--------------------
Number CEU: 2100
Number YRI: 2100
Number for mating: 100
--------------------
Simulating admixed populations

Loading VCF output/sim1/admixed_data/input/ceu_yri_genos.vcf.gz chromosome 20 ...
Chromosome 20 loaded - 898988 SNPs, 200 samples
Breeding generation    8/   8 (100.0%) -    500 diploid individuals     done.
Final simulated population size is 500 diploid individuals
Writing output...       898988/     898988 (100.0) SNPs     done.

Simulating true PRS for iteration=1
-----------------------------
Sample Training/Testing Split
-----------------------------
Cases CEU = 100
Cases YRI = 100
Controls CEU = 100
Controls YRI = 100
Testing CEU = 500
Testing YRI = 500
Testing admixed (CEU+YRI) = 500
-----------------------------
Extracting proportion ancestry at PRS variants
Computing SNP MAF for CEU. GWAS will be performed for SNPs with maf > 1%
100%|████████████████████████████████████████████████████████████▉| 897903/898988 [00:46<00:00, 19352.30it/s]Running GWAS for population = CEU
------------------- # cases = 100
------------------- # sites = 127237


100%|█████████████████████████████████████████████████████████████| 898988/898988 [00:59<00:00, 19352.30it/s-----------------------------------███████████████████████████████▉| 898515/898988 [01:06<00:00, 12720.09it/s]
Selecting variants for PRS building
-----------------------------------
Population used for LD clumping = ceu
Parameters: p-value = 0.01 and r2 = 0.2
# variants with p < 0.01: 4715
Clumping variants...
                                                                                                            # variants after clumping: 92██████████████████████████████████████| 898988/898988 [01:21<00:00, 12720.09it/s]
-----------------------------------
                                                                                                            Creating empricial with CEU selected snps and CEU weights
..... for the CEU population██████████████████████████████████████| 898988/898988 [01:05<00:00, 19337.17it/s]
..... for the YRI population
..... for the admixed population
/home/users/bbchu/miniconda3/envs/prs_sim/lib/python3.7/site-packages/numpy/core/_methods.py:140: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims)
Traceback (most recent call last):
  File "/home/users/bbchu/miniconda3/envs/prs_sim/lib/python3.7/site-packages/statsmodels/nonparametric/kde.py", line 455, in kdensityfft
    bw = float(bw)
ValueError: could not convert string to float: 'scott'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_simulation.py", line 58, in <module>
    args.decrease_samples_yri,args.output_dir,args.threads)
  File "run_simulation.py", line 37, in main
    snp_selection=snp,num2decrease=cases_yri)
  File "/scratch/users/bbchu/PRS_Admixture_Simulation/simulation/summary.py", line 69, in output_all_summary
    snp_weighting,sim,m,h2,r2,p)
  File "/scratch/users/bbchu/PRS_Admixture_Simulation/simulation/summary.py", line 119, in plot_true_vs_empirical
    hist=False,kde=True,kde_kws = {'shade': True, 'linewidth': 3},ax=axes[ind])
  File "/home/users/bbchu/miniconda3/envs/prs_sim/lib/python3.7/site-packages/seaborn/distributions.py", line 231, in distplot
    kdeplot(a, vertical=vertical, ax=ax, color=kde_color, **kde_kws)
  File "/home/users/bbchu/miniconda3/envs/prs_sim/lib/python3.7/site-packages/seaborn/distributions.py", line 691, in kdeplot
    cumulative=cumulative, **kwargs)
  File "/home/users/bbchu/miniconda3/envs/prs_sim/lib/python3.7/site-packages/seaborn/distributions.py", line 283, in _univariate_kdeplot
    cumulative=cumulative)
  File "/home/users/bbchu/miniconda3/envs/prs_sim/lib/python3.7/site-packages/seaborn/distributions.py", line 355, in _statsmodels_univariate_kde
    kde.fit(kernel, bw, fft, gridsize=gridsize, cut=cut, clip=clip)
  File "/home/users/bbchu/miniconda3/envs/prs_sim/lib/python3.7/site-packages/statsmodels/nonparametric/kde.py", line 142, in fit
    clip=clip, cut=cut)
  File "/home/users/bbchu/miniconda3/envs/prs_sim/lib/python3.7/site-packages/statsmodels/nonparametric/kde.py", line 457, in kdensityfft
    bw = bandwidths.select_bandwidth(X, bw, kern) # will cross-val fit this pattern?
  File "/home/users/bbchu/miniconda3/envs/prs_sim/lib/python3.7/site-packages/statsmodels/nonparametric/bandwidths.py", line 172, in select_bandwidth
    return bandwidth_funcs[bw](x, kernel)
  File "/home/users/bbchu/miniconda3/envs/prs_sim/lib/python3.7/site-packages/statsmodels/nonparametric/bandwidths.py", line 55, in bw_scott
    return 1.059 * A * n ** (-0.2)
ZeroDivisionError: 0.0 cannot be raised to a negative power
100%|██████████████████████████████████████████████████████████████| 898988/898988 [03:58<00:00, 3765.03it/s]
100%|█████████████████████████████████████████████████████████████| 898988/898988 [01:24<00:00, 10632.48it/s]
```
I'm guessing yesterday I requested too little memory. 

Also, I have a followup question:
+ I would like to access haplotypes from the `CEU`, `YRI`, and admixed samples. Is there a way I can convert the `.hdf` data files to `.vcf` format or something similar? I am not familiar with `.hdf` format.

**Comment by biona001** [comment]
I figured out how to output `.hdf` format to VCF format. 
```python
# usage: 
# python write.py tree_CEU_GWAS_nofilt.hdf > CEU.vcf

import numpy as np
import pandas as pd
import msprime
import h5py
import gzip
import os
import sys

filename = sys.argv[1]
mytree = msprime.load(filename)

# print results (2 is for diploid, "legacy" = no matching positions)
with sys.stdout as vcffile:
    mytree.write_vcf(vcffile, 2)

```

**Comment by taylorcavazos** [comment]
The `ValueError: could not convert string to float: 'scott'` error is a bit of a weird one. 

I get a different error at the same step (`libc++abi: terminating with uncaught exception of type NSException`) when running this on my Mac; however, I don't get the error when I use the same parameters in my HPC environment. 

Even more odd, I used to be able to run this on my Mac and tested it extensively in previous OS versions.

My only current suggestion is to increase the number of samples (a GWAS with only 100 cases and controls isn't well powered anyways). I use `N_CEU=21000, N_YRI=21000, N_MATE=1000, N_ADMIX=5000` on my Mac with no issues, but I still recommend using the values in the original config file. You definitely found a bug that I will try to think through it in the meantime, but please use sample size as a work-around in the meantime.

**Comment by taylorcavazos** [comment]
The `ValueError: could not convert string to float: 'scott'` error is a bit of a weird one.
I get a different error at the same step (`libc++abi: terminating with uncaught exception of type NSException`) when running this on my Mac; however, I don't get the error when I use the same parameters in my HPC environment.

Even more odd, I used to be able to run this on my Mac and tested it extensively in previous OS versions.

I'll have to look into this more, but I'm guessing it has to do with OS rather than a bug in the code. Still I'll have to spend some time thinking about this. 

**P.S. Writing the hdf to vcf is fine if you are only running a couple simulations; however, if you start simulating many large populations I would not recommend this since it will take up a lot of memory and working with the hdf tree structure is very efficient.**

**Comment by taylorcavazos** [comment]
@biona001 it is worth pointing out that your error is occurring at the plotting step. **Are you using all of the same  package versions as in the `requirements.txt` file?** 

Specifically, your code errors out here: https://github.com/taylorcavazos/PRS_Admixture_Simulation/blob/73d499db4a43e334f6a176485d8af44be0f156f8/simulation/summary.py#L68

You could try commenting out this line in the code to see if you are able to run all other summary metrics! (Note: you may need to remove the files in `output/sim1/summary/*` because if it partially finished it may not run again since I only check if one of the files exist).

**Comment by biona001** [comment]
Here are my package versions (only those in requirements.txt are listed)

```
$ conda env list
base                     /home/users/bbchu/miniconda3
prs_sim               *  /home/users/bbchu/miniconda3/envs/prs_sim
```
```
$ conda list
# packages in environment at /home/users/bbchu/miniconda3/envs/prs_sim:
#
# Name                    Version                   Build  Channel
h5py                      2.10.0          nompi_py37h513d04c_102    conda-forge
matplotlib                3.0.3                    py37_1    conda-forge
matplotlib-base           3.0.3            py37h5f35d83_1    conda-forge
msprime                   0.7.0            py37hc8e6159_2    conda-forge
numpy                     1.16.3           py37he5ce36f_0    conda-forge
pandas                    0.24.2           py37hb3f55d8_1    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
scikit-learn              0.20.3           py37ha8026db_1    conda-forge
scipy                     1.2.1            py37h09a28d5_1    conda-forge
seaborn                   0.9.0                      py_2    conda-forge
statsmodels               0.9.0           py37h3010b51_1000    conda-forge
tqdm                      4.32.1                     py_0    conda-forge
tskit                     0.1.5            py37hd352d35_0    conda-forge
```
Only `h5py` is at version 2.10.0 where requirements.txt says it's supposed to be 2.9.0 (unsure why, I may have overlooked some installation error). 

I will try your suggestion sometime later.

**Comment by taylorcavazos** [comment]
I fixed the issue! It was caused by the `seaborn` `distplot` function incompatibility with the `statsmodels` package. Solved by removing `statsmodels`, installing most recent `seaborn` and updating to `histplot`. Everything should work if you download the new repo and redo the virtual environment. Please let me know if you run into any more issues.
